name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  mix_test:
    name: mix test (OTP ${{matrix.pair.otp}} | Elixir ${{matrix.pair.elixir}})

    strategy:
      matrix:
        include:
          - pair:
              elixir: "1.15"
              otp: 25
          - pair:
              elixir: "1.18"
              otp: 27
            lint: lint

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Restore deps and _build cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}

      -  run: mix deps.get

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix test

      - run: mix test --warnings-as-errors
        if: ${{ matrix.lint }}